
import React from 'react';
import { 
  Settings, 
  User, 
  Calendar, 
  MapPin, 
  CirclePlay, 
  ArrowRight, 
  FastForward, 
  Trophy, 
  Users, 
  ChartBarBig, 
  Wallet, 
  Home, 
  UserCheck, 
  ArrowLeftRight, 
  Database, 
  Newspaper, 
  CalendarDays, 
  History, 
  LayoutDashboard, 
  CircleHelp,
  Play, 
  Pause, 
  X, 
  Check, 
  Info, 
  CirclePlus, 
  CircleMinus, 
  TrendingUp, 
  TrendingDown,
  Bot, 
  RefreshCw, 
  Gavel, 
  CalendarRange, 
  Target, 
  Award, 
  Plus, 
  Search, 
  ChevronRight,
  GripVertical, 
  GitCompare,
  TriangleAlert,
  Activity,
  Zap,
  Globe,
  Landmark,
  Smartphone,
  ShieldCheck,
  ChevronDown,
  UsersRound,
  Circle,
  Scale,
  Download,
  Trash2
} from 'lucide-react';

export const Icons = {
  Settings,
  User,
  Calendar,
  Venue: MapPin,
  PlayMatch: CirclePlay,
  ArrowRight,
  Forward: FastForward,
  Trophy,
  Popularity: Users,
  Stats: ChartBarBig,
  Finance: Wallet,
  Home,
  Lineups: UserCheck,
  Transfers: ArrowLeftRight,
  Database,
  News: Newspaper,
  Squad: Users,
  Fixtures: CalendarDays,
  History,
  Editor: LayoutDashboard,
  Help: CircleHelp,
  Play,
  Pause,
  X,
  Check,
  Info,
  PlusCircle: CirclePlus,
  RemoveCircle: CircleMinus,
  TrendingUp,
  TrendingDown,
  Bot,
  RefreshCw,
  Gavel,
  Schedule: CalendarRange,
  Strategy: Target,
  Award,
  Plus,
  Search,
  ChevronRight,
  DragHandle: GripVertical,
  Compare: GitCompare,
  Leagues: CalendarRange,
  Podium: Award,
  ChartPie: ChartBarBig,
  Warning: TriangleAlert,
  Close: X,
  Save: Check, // Fallback
  Delete: X, // Fallback
  Edit: LayoutDashboard, // Fallback
  Filter: Search, // Fallback
  Sort: TrendingUp, // Fallback
  Lock: X, // Fallback
  Unlock: Check, // Fallback
  Back: ArrowRight, // Fallback (should be ArrowLeft but ArrowRight is used for navigation often)
  Activity,
  Target,
  Zap,
  Globe,
  Stadium: Landmark,
  Smartphone,
  ShieldCheck,
  ChevronDown,
  Users: UsersRound,
  CricketBall: Circle,
  AlertTriangle: TriangleAlert,
  Fans: UsersRound,
  FastForward,
  Layout: LayoutDashboard,
  Scale,
  Download,
  Trash2,
};
